### PR TITLE
Fix for User Status

### PR DESCRIPTION
**Pull request by kastov**
Tried to fix #640

"No data" now "Not seen"

Seems like #640 not work stable for ALL people. Many people in Telegram reported than status won't shown correctly.

### CODE REVIEW

**Comment by Iambabyninja** [comment]
It's solved problem, but need full check PR:
[#640](https://github.com/Gozargah/Marzban/pull/640) for another errors

**Comment by Iambabyninja** [comment]
It's solved problem, but need full check PR:
[#640](https://github.com/Gozargah/Marzban/pull/640) for another errors

**Comment by kastov** [comment]
**Red** is typically associated with "stop" or "unavailable," so using it to indicate "never connected" makes sense as it signifies a complete lack of activity.
**Orange** serves as an intermediary color between red (stop) and green (go). It could be used to signify that a user was recently active but is not active at the moment.

**Comment by Iambabyninja** [comment]
> **Red** is typically associated with "stop" or "unavailable," so using it to indicate "Not seen" makes sense as it signifies a complete lack of activity.
> 
> 
> 
> **Orange** serves as an intermediary color between red (stop) and green (go). It could be used to signify that a user was recently online but is not online at the moment.

На вкус и цвет, как говорится... 
my opinion is that the original colors were chosen correctly. 
🟢green is online.
🔴red, as its complete opposite, is offline. 
🟡yellow - status is not defined

**Comment by kastov** [comment]
> > **Red** is typically associated with "stop" or "unavailable," so using it to indicate "Not seen" makes sense as it signifies a complete lack of activity.
> > **Orange** serves as an intermediary color between red (stop) and green (go). It could be used to signify that a user was recently online but is not online at the moment.
> 
> На вкус и цвет, как говорится... my opinion is that the original colors were chosen correctly. 🟢green is online. 🔴red, as its complete opposite, is offline. 🟡yellow - status is not defined

Sorry, i did not get that part of your text which is in Russian language.

But, as you wish.

**Comment by VladimirFedulov** [comment]
@SaintShit could you check it?

**Comment by iamtheted** [comment]
Hello there!

I believe "Not Seen" doesn't imply the intended term here.
Online, Offline and the third status is that the user has not connected yet. 
Let's think of some other name for that.

maybe like: 
"Not Connected Yet"
"Awaiting Connection" 
"Neutral"
"Connection Pending"

**Comment by x0sina** [comment]
I think "ago" part is removed after the last online why?

**Comment by kastov** [comment]
> Hello there!
> 
> I believe "Not Seen" doesn't imply the intended term here. Online, Offline and the third status is that the user has not connected yet. Let's think of some other name for that.
> 
> maybe like: "Not Connected Yet" "Awaiting Connection" "Neutral" "Connection Pending"



> Not Connected Yet

Ooops, my fault. Fixed.

**Comment by x0sina** [comment]
Sorry for overasking
but not connected yet "ago" shoud not be in not connected string

**Comment by kastov** [comment]
> Sorry for overasking but not connected yet "ago" shoud not be in not connected string

Yeah-yeah, i see. I'm not pushed yet.

**Pull request merged**
