### PR TITLE
Setup-CORS-policies

### PR DESCRIPTION
**Pull request by loghmanb**
- add allowed origins to CORS-middleware. By default, all origins are allowed but you could restrict by setting the `ALLWED_ORIGINS` env variable

### CODE REVIEW

**Comment by M03ED** [comment]
good job.
but your pr wants to merge 1 commit into master branch
please change branch to dev

**Review by erfjab — APPROVED** [review]

**Comment by erfjab** [comment]
Hello, that's a great idea. Thank you. Please fix git.

**Comment by hamidmayeli** [comment]
Wonderful job @loghmanb, but could we have the default be the same domain name as UI dashboard?

**Comment by loghmanb** [comment]
> Wonderful job @loghmanb, but could we have the default be the same domain name as UI dashboard?
Thanks @hamidmayeli 
I think it might be better to have `*` as the default value since we want to have backward compatibility
https://github.com/Gozargah/Marzban/pull/1206/files#diff-9cec7b11237bc29d77a439e81c9b7acfac003d8e8855731eb6bc130b5a8ce602L29

**Comment by hamidmayeli** [comment]
Hi @M03ED, could you please merge this PR? Also, when would this be released?

**Comment by M03ED** [comment]
> Hi @M03ED, could you please merge this PR? Also, when would this be released?

I don't have access to merge

**Comment by erfjab** [comment]
> Hi @M03ED, could you please merge this PR? Also, when would this be released?

Wait for boss :)

**Pull request merged**
