### PR TITLE
refact: marzban

### PR DESCRIPTION
**Pull request by erfjab**

### CODE REVIEW

**Comment by happybigboy** [comment]
please merge, so important 😄🙏

**Review by MatinDehghanian — APPROVED** [review]

**Review by happybigboy — APPROVED** [review]

**Comment by Musixal** [comment]
422 files changed by Erfan. Great work. Special version of Marzban w/o any bugs.

**Comment by MatinDehghanian** [comment]
You finally found best way to refactoring the marzban

**Comment by happybigboy** [comment]
I'm using it right now, so much speed and goid work from erfan, need a raise 🙌

**Comment by mikeesierrah** [comment]
Show this to the one who asked for a no-bug version they really need it

**Comment by MatinDehghanian** [comment]
Add a branch and name it “MadBan” and merge into that,
And now “mad” can put all of his requests into his ass <3

**Comment by MatinDehghanian** [comment]
> Add a branch and name it “MadBan” and merge into that, And now “mad” can put all of his requests into his ass <3

از قسمت پاچه شلوارکش🙏🏻

**Comment by M03ED** [comment]
What a wonderful coding skill 
Marzban will be perfect after this pr.

**Comment by MatinDehghanian** [comment]
> I heard ALLOWED_ORIGINS was added by you Erfan, and It seems it doesn't really work. You might want to double check everything after you copy paste it from ChatGPT.

Before that,
Marzban team should learn react.js and router
And use components folder for each section
Now when i look project , one component have 8000 lines of code.


> I heard ALLOWED_ORIGINS was added by you Erfan, and It seems it doesn't really work. You might want to double check everything after you copy paste it from ChatGPT.

Before that,
Marzban team should learn react.js and router
And use components folder for each section
Now when i look project , one component have 8000 lines of code.

Merge this pr, and use ChatGPT to learn coding and development

**Comment by iamtheted** [comment]
I believe I have to remind you all of few points.

1.You keep comparing projects that if Marzban wants to surpass other projects, it has to do this and that, but the truth is Marzban's developers don't see it as a competition. People decide what to use based on what they need so it's not a race at all.

2.ChatGPT is a good tool to start learning things just like how I used GPT to come up with Transfer-Me but in a massive project like Marzban, I don't believe GPT alone is enough. Even if you use GPT, you need to check to make sure it works as expected. This isn’t the first time GPT-generated code has messed things up because it wasn’t properly reviewed.

3.If you want to help, please focus on adding practical features. For example, Host Order is of no use unless we can move an inbound’s host above another. Since we can’t do that, we’d be better off without it.

4.What are you even doing here? I thought you found another project that you believe is far better than Marzban, so why not stick with that?

**Comment by MatinDehghanian** [comment]
We are not here to hear ur needs,
You can submit issue your request and ur needs and ur priorities 
As a developer, i commit anything i want, and ur opinion is not my priority.
Btw i wasted my time for committing commits in Marzban, cause marzban is not using correct formatting folders and components,
And it’s very not-friendly for developers. And got double time from me .

After all of this comments, <<when i compared marzban to another project?>>
I just told u this project is not using correct components style and render style

**Pull request closed without merging**
