### PR TITLE
add NOTICE for notify user when account is inactive

### PR DESCRIPTION
**Pull request by erfjab**
With this feature, you can set a specific inbound configuration so that when users become inactive, only the configs related to that inbound are sent during updates. Also, when the user is active or awaiting activation, these configs won't be displayed to them.

To activate this feature, the user must have that inbound. Additionally, even if it’s set up incorrectly, the system will continue to function without any issues.

### CODE REVIEW

**Comment by erfjab** [comment]
https://github.com/Gozargah/Marzban/assets/143827987/aafedc64-f706-4849-995c-16d808e7e173

I recorded a video to show how this feature works.

Notes:

- I named the inbound "NOTICE," but you can choose any name you like.
- You can set up thousands of hosts with different messages for this inbound.
- I enabled the randomization of configs.

**Comment by erfjab** [comment]
For limited and expired users, this feature is enabled. For active and on-hold users, it's disabled. This feature doesn't change any data. We don't alter the users' inbounds and proxies in the database. We only filter the inbound and proxy data we get from the user. This method is super efficient and hassle-free because I previously implemented this capability for HolderBot (a separate bot for managing Marzban) and fixed all the issues I encountered.

**Comment by erfjab** [comment]
**And of course it is optional**

**Comment by iamtheted** [comment]
This is simply fantastic!!! 
I appreciate you bro. 💙

**Comment by iamtheted** [comment]
The cool thing is, it won't exclude the user's proxies so you'd forget what inbounds you have included for the user. It only prevents them from displaying in the list after user updates the subscription. 😍

**Comment by erfjab** [comment]
image

test get user api.

**Comment by ImMohammad20000** [comment]
its better to use empty string or None  as default value for NOTICE_INACTIVE_USERS in config,py

**Comment by AmoAlireza** [comment]
thanks for this amazing PR ❤ @erfjab 

i try this PR and everything working fine, but there is bug with inbound protocol, when you have another inbound in same protocol with `NOTICE_INACTIVE_USERS` this will disable whole protocol not only the inbound we set.

example:
like we have 2 `vmess` inbound with names `NOTICE_INBOUND` & `VMESS_CONFIG`, in this point the `VMESS_CONFIG` inbound will disable too and it's like the protocol will disabled.

**Comment by erfjab** [comment]
> thanks for this amazing PR ❤ @erfjab 
> 
> i try this PR and everything working fine, but there is bug with inbound protocol, when you have another inbound in same protocol with `NOTICE_INACTIVE_USERS` this will disable whole protocol not only the inbound we set.
> 
> example:
> like we have 2 `vmess` inbound with names `NOTICE_INBOUND` & `VMESS_CONFIG`, in this point the `VMESS_CONFIG` inbound will disable too and it's like the protocol will disabled.

Thank you for your test and report. Do you mean that the Vmess protocol is completely removed? I had been monitoring this issue and had prevented it, but I will definitely review it again and make the necessary corrections.

**Comment by AmoAlireza** [comment]
> > thanks for this amazing PR ❤ @erfjab
> > i try this PR and everything working fine, but there is bug with inbound protocol, when you have another inbound in same protocol with `NOTICE_INACTIVE_USERS` this will disable whole protocol not only the inbound we set.
> > example:
> > like we have 2 `vmess` inbound with names `NOTICE_INBOUND` & `VMESS_CONFIG`, in this point the `VMESS_CONFIG` inbound will disable too and it's like the protocol will disabled.
> 
> Thank you for your test and report. Do you mean that the Vmess protocol is completely removed? I had been monitoring this issue and had prevented it, but I will definitely review it again and make the necessary corrections.

yeah the vmess protocol was completely removed because i put notice inbound in same protocol i use for my configs.

**Comment by AmoAlireza** [comment]
find another bug @erfjab 

when you open subscription link in your browser this will show the NOTICE_INBOUND too.

**Comment by erfjab** [comment]
> find another bug @erfjab 
> 
> when you open subscription link in your browser this will show the NOTICE_INBOUND too.

There needs to be a better system for NOTICE.

**Comment by AmoAlireza** [comment]
> thanks for this amazing PR ❤ @erfjab
> 
> i try this PR and everything working fine, but there is bug with inbound protocol, when you have another inbound in same protocol with `NOTICE_INACTIVE_USERS` this will disable whole protocol not only the inbound we set.
> 
> example: like we have 2 `vmess` inbound with names `NOTICE_INBOUND` & `VMESS_CONFIG`, in this point the `VMESS_CONFIG` inbound will disable too and it's like the protocol `vmess` will disabled.

@erfjab 
fix for this issues:

```python
def manage_notice(user: "UserResponse"):
    if not any(NOTICE_INACTIVE_USERS in inbounds for inbounds in user.inbounds.values()):
        return user.inbounds, user.proxies

    filtered_inbounds = {}
    filtered_proxies = {}

    if user.status in ['active', 'on_hold']:
        for protocol, inbounds in user.inbounds.items():
            filtered_inbounds[protocol] = [inbound for inbound in inbounds if inbound != NOTICE_INACTIVE_USERS]
            if filtered_inbounds[protocol]:  # Only include non-empty inbound lists
                filtered_proxies[protocol] = user.proxies.get(protocol, {})
    else:  # For disabled or limited users
        for protocol, inbounds in user.inbounds.items():
            if NOTICE_INACTIVE_USERS in inbounds:
                filtered_inbounds[protocol] = [NOTICE_INACTIVE_USERS]
                filtered_proxies[protocol] = user.proxies.get(protocol, {})

    return filtered_inbounds, filtered_proxies

**Comment by erfjab** [comment]
> > thanks for this amazing PR ❤ @erfjab
> > 
> > i try this PR and everything working fine, but there is bug with inbound protocol, when you have another inbound in same protocol with `NOTICE_INACTIVE_USERS` this will disable whole protocol not only the inbound we set.
> > 
> > example: like we have 2 `vmess` inbound with names `NOTICE_INBOUND` & `VMESS_CONFIG`, in this point the `VMESS_CONFIG` inbound will disable too and it's like the protocol `vmess` will disabled.
> 
> @erfjab 
> fix for this issues:
> 
> ```python
> def manage_notice(user: "UserResponse"):
>     if not any(NOTICE_INACTIVE_USERS in inbounds for inbounds in user.inbounds.values()):
>         return user.inbounds, user.proxies
> 
>     filtered_inbounds = {}
>     filtered_proxies = {}
> 
>     if user.status in ['active', 'on_hold']:
>         for protocol, inbounds in user.inbounds.items():
>             filtered_inbounds[protocol] = [inbound for inbound in inbounds if inbound != NOTICE_INACTIVE_USERS]
>             if filtered_inbounds[protocol]: 
>                 filtered_proxies[protocol] = user.proxies.get(protocol, {})
>     else:
>         for protocol, inbounds in user.inbounds.items():
>             if NOTICE_INACTIVE_USERS in inbounds:
>                 filtered_inbounds[protocol] = [NOTICE_INACTIVE_USERS]
>                 filtered_proxies[protocol] = user.proxies.get(protocol, {})
> 
>     return filtered_inbounds, filtered_proxies

Thank you, after checking and testing the errors, I will update the pr. 🤌❤️

**Comment by erfjab** [comment]
> thanks for this amazing PR ❤ @erfjab
> 
> i try this PR and everything working fine, but there is bug with inbound protocol, when you have another inbound in same protocol with `NOTICE_INACTIVE_USERS` this will disable whole protocol not only the inbound we set.
> 
> example: like we have 2 `vmess` inbound with names `NOTICE_INBOUND` & `VMESS_CONFIG`, in this point the `VMESS_CONFIG` inbound will disable too and it's like the protocol `vmess` will disabled.

I tested the notice again and found no problems. Tell me more about your problem.

**Comment by AmoAlireza** [comment]
> > thanks for this amazing PR ❤ @erfjab
> > i try this PR and everything working fine, but there is bug with inbound protocol, when you have another inbound in same protocol with `NOTICE_INACTIVE_USERS` this will disable whole protocol not only the inbound we set.
> > example: like we have 2 `vmess` inbound with names `NOTICE_INBOUND` & `VMESS_CONFIG`, in this point the `VMESS_CONFIG` inbound will disable too and it's like the protocol `vmess` will disabled.
> 
> I tested the notice again and found no problems. Tell me more about your problem.

make 2~3 vmess inbound then test it, when user is active or on_hold the other vmess configs will not showing to user after update hes sub link, even after user are disabled or limited when user update hes sub link the vmess configs not showing to the user because they all are vmess protocol.
it seem the codes effect on whole protocol not the inbound we set for it.
```json
{
      "tag": "NOTICE_INBOUND",
      "listen": "0.0.0.0",
      "port": 1,
      "protocol": "vmess",
      "settings": {
        "clients": []
      },
      "streamSettings": {}
    },
    {
      "tag": "CONFIG1",
      "listen": "0.0.0.0",
      "port": 2,
      "protocol": "vmess",
      "settings": {
        "clients": []
      },
      "streamSettings": {}
    },
    {
      "tag": "CONFIG2",
      "listen": "0.0.0.0",
      "port": 3,
      "protocol": "vmess",
      "settings": {
        "clients": []
      },
      "streamSettings": {}
    }

**Comment by erfjab** [comment]
i fix all.

**Comment by AmoAlireza** [comment]
> i fix all.



> find another bug @erfjab
> 
> when you open subscription link in your browser this will show the NOTICE_INBOUND too.

this bug fixed too?

**Comment by erfjab** [comment]
> > i fix all.
> 
> > find another bug @erfjab
> > when you open subscription link in your browser this will show the NOTICE_INBOUND too.
> 
> this bug fixed too?

Yes, you can test and give me feedback. thank you

**Comment by AmoAlireza** [comment]
> > > i fix all.
> > 
> > 
> > > find another bug @erfjab
> > > when you open subscription link in your browser this will show the NOTICE_INBOUND too.
> > 
> > 
> > this bug fixed too?
> 
> Yes, you can test and give me feedback. thank you

everything working fine, thanks 👌

**Comment by erfjab** [comment]
I should write better

**Comment by erfjab** [comment]
> Can you add a feature where if the user is using a version like V2rayNG/1.8.28 or earlier, and they update the old V2ray server version, the servers are deleted, leaving only one server that shows a message indicating the app version is outdated and needs to be updated. This should be controlled via User-Agent.
> 
> It would also be better if the program name, the latest version, and the usable versions could be configured in a `.env` file. Thanks.

Hi ,Marzban does not accept this.

**Comment by erfjab** [comment]
So it should be personalized for you. For help, you can ask questions in the official Marzban group.

**Pull request closed without merging**
