### PR TITLE
fix geoip and geosite download problem

### PR DESCRIPTION
**Pull request by oXIIIo**
- fix the issue of not being able to download geoip and geosite files in the sing-box template
- format the template files with the sing-box formatter

### CODE REVIEW

**Comment by M03ED** [comment]
This is a good merge, but there are other bugs in the 'sing box' that need fixing. We are waiting to identify all the bugs before fixing them all at once. Also, you removed some unused values from the template. I added them to the default template for people who want to personalize it and see their options.

**Comment by M03ED** [comment]
And for geoip file problem we just need to add this line 
      "download_detour": "direct"

**Comment by oXIIIo** [comment]
As I mentioned, it has been formatted by the "sing-box" formatter, and for this reason, some unnecessary initializations have been removed. Additionally, in the end, users need to read the "sing-box" document to understand the purpose of each section.
as you can see clash config is minimal as possible.

**Comment by master88wi** [comment]
sing-box good

**Pull request merged**
