### PR TITLE
Add User Status online/offline - Last Seen

### PR DESCRIPTION
**Pull request by x0sina**
photo_2023-11-17_20-36-51

1. If User online_at data is less than 60 seconds to now user is online
2. If User online_at data is more than 60 seconds to now user is offline - and can access last seen
3. If User online_at data is null we have nodata option

### CODE REVIEW

**Comment by SaintShit** [comment]
Nice, thank you!

**Comment by VladimirFedulov** [comment]
It doesn't work for me with VLESS TCP REALITY

**Comment by x0sina** [comment]
This Pull Request is only front-end 

> It doesn't work for me with VLESS TCP REALITY

This commits is only client side and type of config is not important because data of user online status will sent from backend and database, it should work with any type of configs

**Comment by x0sina** [comment]
> Nice, thank you!

Thanks for merging❤️

**Comment by kastov** [comment]
> > Nice, thank you!
> 
> Thanks for merging❤️

#644 can you check please? Seems like your PR did not work correctly for some users.

**Pull request merged**
