### PR TITLE
Users auto-delete implemented.

### PR DESCRIPTION
**Pull request by Alirezaja1384**
TODO:
 - Send notifications

### CODE REVIEW

**Comment by xmohammad1** [comment]
thats really good

**Comment by Alirezaja1384** [comment]
Easier than expected :)

P.S. I didn't have time to test the notifications, but I don't see any reason for them not working.

**Comment by M03ED** [comment]
thanks for this pr
first of all can you explain we have 3 migration here ? all of these can be one migration 
and for the next you are making new logger for just single job, marzban already have a logger , you can just use that

**Comment by Alirezaja1384** [comment]
> first of all can you explain we have 3 migration here ? all of these can be one migration

Ok, I'm convinced. 3 is too much. I'll merge them :)

> and for the next you are making new logger for just single job, marzban already have a logger , you can just use that

I was in a hurry and didn't see it. thanks for your suggestion.

**Comment by Alirezaja1384** [comment]
Sounds like I'm late to the party. I just merged the migrations :/

**Pull request merged**
