### PR TITLE
Fix(users): add ilike to get user

### PR DESCRIPTION
**Pull request by erfjab**
A small change for me, but a big change for tgbots. :)

### CODE REVIEW

**Comment by M03ED** [comment]
this is for finding exact username, if you want to find similar username use `get_users`

**Comment by erfjab** [comment]
> this is for finding exact username, if you want to find similar username use `get_users`
> 

My goal was to be able to get a user's information regardless of whether it is upper or lower.

**Comment by M03ED** [comment]
marzban database is sensitive to upper case and lower case 
you can have `user` and `User` at same time so this can cause lots of bugs
so i close this pr

**Comment by erfjab** [comment]
> marzban database is sensitive to upper case and lower case 
> you can have `user` and `User` at same time so this can cause lots of bugs
> so i close this pr

Ok.

**Pull request closed without merging**
