### PR TITLE
On Hold Property Added to UserDialog | Usage Coefficient Added to NodesModal

### PR DESCRIPTION
**Pull request by x0sina**
Coefficient
Screenshot 2024-07-19 224321

### CODE REVIEW

**Comment by SaintShit** [comment]
Nice! we've needed this for a long time.
Can you please make the "Expire duration" field required when the On_hold is checked? otherwise, this error will throw

image

and it's not catched.

**Comment by M03ED** [comment]
also this change is on master branch not dev branch

**Comment by x0sina** [comment]
Thanks for reviewing my pull request
Expire duration is now required in UserDialog when trying to create or edit a user on on_hold' status.

**Comment by M03ED** [comment]
Thanks for this, but we should not be able to change user status to on_hold when we edit the user ?

**Pull request merged**
