### PR TITLE
fix: custom configs not work on version 1.8.16 & 1.8.17 of v2rayng

### PR DESCRIPTION
**Pull request by m0x61h0x64i**
on v2rayng, custom configs only work on version 1.8.18 or later

### CODE REVIEW

**Comment by M03ED** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.8.16

**Comment by m0x61h0x64i** [comment]
download and test this : https://github.com/2dust/v2rayNG/releases/tag/1.8.17

**Comment by M03ED** [comment]
when i write v2ray json config 1.8.18 was not released

**Comment by m0x61h0x64i** [comment]
ok, just test 1.8.17 with xray template on

**Comment by M03ED** [comment]
I test both 1.816 and 1.8.17 right now 
I'm connected with 1.8.17 version and sending this message

**Comment by m0x61h0x64i** [comment]
Do ur configs are customize config at version 1.8.17 ?

**Comment by M03ED** [comment]
> Do ur configs are customize config at version 1.8.17 ?

Yes

**Comment by m0x61h0x64i** [comment]
Do u use xray template ?

https://github.com/WhyMan1/marzban-template/tree/master/v2ray

**Comment by M03ED** [comment]
I'm using the default template, if you're using a third party template and you can't use custom config so that the problem ,is not marzban

**Pull request closed without merging**
