### PR TITLE
add login notife

### PR DESCRIPTION
**Pull request by erfjab**
With this feature, all Marzban logins (successful or unsuccessful) are notified. In case of a successful login, it hides the password and shows the username. In case of an unsuccessful login, it shows both the username and password together.

### CODE REVIEW

**Comment by erfjab** [comment]
https://github.com/Gozargah/Marzban/assets/143827987/fb01b082-a9b4-463d-98ff-20617362f89e

**Comment by AmoAlireza** [comment]
nice PR 👍
can you add user IP failed to connect too?

**Comment by erfjab** [comment]
> nice PR 👍
> can you add user IP failed to connect too?

Thank you ♥️, yes, I was thinking about it, I will update it soon.

**Comment by erfjab** [comment]
#909

**Pull request merged**
