### PR TITLE
fix: splithttp and alpn

### PR DESCRIPTION
**Pull request by M03ED**
- add missing parameters for splithttp #1076
- fix alpn bug #1034

### CODE REVIEW

**Comment by M03ED** [comment]
- fix for #798 in commit [e22bf9b](https://github.com/Gozargah/Marzban/pull/1077/commits/e22bf9b0284f0a519c899bd08c010e62de50f07b)

**Comment by iambabyninja** [comment]
My dear friend, big thanx 4 your work.

Default values for this parameters:

func (c *Config) GetNormalizedMaxConcurrentUploads() int32 {
	if c.MaxConcurrentUploads == 0 {
		return 10
	}

	return c.MaxConcurrentUploads
}

func (c *Config) GetNormalizedMaxUploadSize() int32 {
	if c.MaxUploadSize == 0 {
		return 1000000
	}

	return c.MaxUploadSize
}

**Comment by M03ED** [comment]
> The value should be set in bytes, accordingly, the standard recommended chunk size of 1MB should be set to approximately 1,000,000 bytes.

done.

**Comment by fodhelper** [comment]
Please change initial_windows_size to 35536 to make cloudflare grpc configs work
image
https://xtls.github.io/en/config/transports/grpc.html#grpcobject

**Pull request merged**
