### PR TITLE
add node error monitoring

### PR DESCRIPTION
**Pull request by erfjab**
With this feature, you will be notified whenever there is a problem connecting the nodes.
#1108

### CODE REVIEW

**Comment by erfjab** [comment]
image
For example

**Comment by M03ED** [comment]
in current implementation when node get error and stuck their we gonna get a spam message from marzban , every 10 second we receive new message 
i tried to write this before and i didn't find good way to avoid spam

**Comment by erfjab** [comment]
> in current implementation when node get error and stuck their we gonna get a spam message from marzban , every 10 second we receive new message i tried to write this before and i didn't find good way to avoid spam

Of course, there is a way, but it is not very professional, here we can add that it will wait 60 seconds after every error, but we will be forced to ignore the scheduler error. 😅


image

**Comment by erfjab** [comment]
I should write better

**Pull request closed without merging**
