### PR TITLE
record usages per hour

### PR DESCRIPTION
**Pull request by zhongfq**
Record per hour:
| id |         created_at         | user_username | node_id | used_traffic |
|----|----------------------------|---------------|---------|--------------|
| 1  | 2023-05-07 16:00:00.000000 | codetypes     | 1       | 3736004      |
| 2  | 2023-05-07 16:00:00.000000 | codetypes     | 5       | 7929329      |
| 3  | 2023-05-07 16:00:00.000000 | codetypes     | 4       | 518          |

| id |         created_at         | node_id |  uplink  | downlink |
|----|----------------------------|---------|----------|----------|
| 1  | 2023-05-07 05:00:00.000000 | 4       | 203955   | 14468077 |
| 2  | 2023-05-07 05:00:00.000000 | 5       | 30643    | 680743   |
| 3  | 2023-05-07 06:00:00.000000 | 5       | 27228    | 331378   |
| 4  | 2023-05-07 08:00:00.000000 | 5       | 75617    | 414471   |
| 5  | 2023-05-07 09:00:00.000000 | 5       | 11478    | 29287    |
| 6  | 2023-05-07 11:00:00.000000 | 5       | 1773     | 31446    |
| 7  | 2023-05-07 12:00:00.000000 | 5       | 167312   | 453009   |
| 8  | 2023-04-23 15:00:00.000000 | 5       | 10299221 | 10299221 |
| 11 | 2023-05-04 15:00:00.000000 | 5       | 10299221 | 10299221 |
| 12 | 2023-05-06 15:00:00.000000 | 5       | 10299221 | 10299221 |

IMG_23A6AAD1C780-1
IMG_0767B5D5062D-1

### CODE REVIEW

**Comment by Elhwm** [comment]
@zhongfq چقدر این چینیه خوبه واقعا

**Comment by s4I3h** [comment]
@zhongfq Tnx

**Comment by M03ED** [comment]
it need one more option , all.

**Comment by SaintShit** [comment]
Hi, sorry for being late, is there any reason why this was deleted? I think this was a great feature!

**Comment by Musixal** [comment]
@SaintShit Please merge this feature to dev branch. Nice and useful feature imo.

**Comment by SaintShit** [comment]
> @SaintShit Please merge this feature to dev branch. Nice and useful feature imo.

The PR's closed, He should make another PR.

**Comment by zhongfq** [comment]
> Hi, sorry for being late, is there any reason why this was deleted? I think this was a great feature!

i try to use user_id instead of username to record usage, i make 'userid.username' pass to xray,  and then i can get userid in record usage.

**Comment by zhongfq** [comment]
> > @SaintShit Please merge this feature to dev branch. Nice and useful feature imo.
> 
> The PR's closed, He should make another PR.

i will push request in few days later, i want to make it more useable

**Comment by SaintShit** [comment]
> > > @SaintShit Please merge this feature to dev branch. Nice and useful feature imo.
> > 
> > 
> > The PR's closed, He should make another PR.
> 
> i will push request in few days later, i want to make it more useable

Alright, thanks for your efforts.

**Comment by SaintShit** [comment]
@zhongfq Hi, I've some serious issues with the way NodeUserUsages are currently logged, in some cases, it gets stuck with db error ( IntegrityError caused by unique constraint which I've added to ensure uniqueness of records ) and doesn't update user usage anymore. I think we have to come up with a new implementation for it.

**Comment by zhongfq** [comment]
> @zhongfq Hi, I've some serious issues with the way NodeUserUsages are currently logged, in some cases, it gets stuck with db error ( IntegrityError caused by unique constraint which I've added to ensure uniqueness of records ) and doesn't update user usage anymore. I think we have to come up with a new implementation for it.

In my vps server, i didn't find this error, it run ok for weeks

**Pull request closed without merging**
