### PR TITLE
[Update]: add sort by expiration date feature. #348

### PR DESCRIPTION
**Pull request by MR-MKZ**
Changes to be committed:
	modified:   app/dashboard/src/components/UsersTable.tsx

### CODE REVIEW

**Comment by MR-MKZ** [comment]
### Tasks:
- [x] Add sort by expiration date
### Modified files:
- UsersTable.tsx
### Changes screenshots:
- Without expiration date sort
Screenshot 2024-07-14 082256
- Sorting based on those whose subscription ends first
Screenshot 2024-07-14 082325
- Sorting based on those whose subscription ends later
Screenshot 2024-07-14 082351

**Comment by ImMohammad20000** [comment]
good change thanks

**Comment by M03ED** [comment]
this change its only in front, its not how it should be
front should not sort data , you should change request parameter and get sorted data from backend
https://github.com/Gozargah/Marzban/blob/dev/app/db/crud.py#L104
https://github.com/Gozargah/Marzban/blob/dev/app/views/user.py#L226
also you apply this change on master branch and that's not allowed , you should work with dev branch

**Comment by MR-MKZ** [comment]
I know and I don't sort data in front-end.
I'm using filters.sort which it's send a request to backend with parameter expire and backend returns sorted data based on expire date.

**Comment by MR-MKZ** [comment]
And thanks for your advise, I changed branch to dev.

**Comment by MR-MKZ** [comment]
image
I'm using this parameter

**Comment by iamtheted** [comment]
This is amazing 😍
I have been wanting this for so long!
Thank you for the PR mate @MR-MKZ

**Comment by MR-MKZ** [comment]
You're welcome bro ❤️

**Pull request merged**
