### PR TITLE
feat: Add migration to correct last_status_change for expired users

### PR DESCRIPTION
**Pull request by Alirezaja1384**
P.S. I don't know if handling only MySQL and SQLite is enough or not.

### CODE REVIEW

**Review by erfjab — COMMENTED** [review]
Friends also use Mariadb, but the Mariadb and MySQL commands are similar.

**Comment by SaintShit** [comment]
Hi, would you please explain what problem is solves?

**Comment by Alirezaja1384** [comment]
> Hi, would you please explain what problem it solves?

Sure, the migration I wrote before sets that `last_status_change` to migration time, so if we suppose the expired should be deleted in 30 days, they will be deleted a month after the migration, not their expiration date. This migration sets the `last_status_change` to the user's expiration time.

**Comment by ImMohammad20000** [comment]
what if user expire is null??

**Comment by ImMohammad20000** [comment]
> what if user expire is null??

@Alirezaja1384

**Pull request merged**
