### PR TITLE
Update Pydantic version and refactor model validators

### PR DESCRIPTION
**Pull request by MahdiButcher**
Upgrade Pydantic to version 2.10.2 and refactor model validators to use the new syntax and features. This improves code consistency and leverages the latest enhancements in Pydantic.

### CODE REVIEW

**Comment by ImMohammad20000** [comment]
Hi thanks for ur pr change target branch to dev

**Review by M03ED — CHANGES_REQUESTED** [review]
Code it's not sync with dev version 
and did you test all field validators ?

**Comment by MahdiButcher** [comment]
okay mo3ed , I will sync it with dev branch

**Comment by MahdiButcher** [comment]
I will close this pull to make a new one for exclusively for dev branch

**Pull request closed without merging**
