### PR TITLE
Proxy host: security option implemented

### PR DESCRIPTION
**Pull request by Alirezaja1384**
Details:
 - ProxyHost's security field implemented which has 3 options:
   * Inbound's default: Follows the inbound's security settings (default)
   * None: Disables TLS
   * TLS: Enables TLS

Use cases:
 - When TLS is not handled by xray and it doesn't know about it. For example, nginx can be used as a reverse proxy and handle the TLS stuff itself.

### CODE REVIEW

**Comment by SaintShit** [comment]
Hi, thanks for your contribution, this feature you added is useful, however, some parts need to be changed in the host, so I will merge it and make changes after that.

**Comment by Alirezaja1384** [comment]
You're welcome. I also fixed the conflicts and a stupid mistake I didn't notice before, If there's anything wrong with it, I'll be happy to fix it.

**Comment by SaintShit** [comment]
Alright thanks, I'll do the rest.

**Comment by Alirezaja1384** [comment]
I accidentally committed the changes I made to xray.json. There are some conflicts now. I'll fix them asap. I think it may be better to add xray.json to .gitignore and rename it to something like xray.exmaple.json. Like what you did for .env.

**Comment by SaintShit** [comment]
I noticed that you pushed your xray.json, no problem. I won't accept changes of xray.json on merge. btw you can make a file named xray-dev.json or any *-custom.json file to change it locally.

**Comment by Alirezaja1384** [comment]
Thank you. It seems the dev branch has some bugs. it says `No inbound found. Please check your Xray config file.`. Just in case, you didn't notice yet.

**Comment by Alirezaja1384** [comment]
And about the xray-dev.json, I didn't see any documentation about the contribution. It might be a good idea to have something like CONTRIBUTE.md and explain such things there. Free software highly depends on contributions!

**Pull request merged**
