### PR TITLE
support multi-language and reset all usage

### PR DESCRIPTION
**Pull request by zhongfq**
add reset button to reset all usage and system usage record

multi-language
IMG_0639
IMG_0640

### CODE REVIEW

**Comment by zhongfq** [comment]
table header display error
IMG_CD94FC351E45-1

use 'Accordion' instead of 'Table' in small screen(w<768).
Screenshot_2023-04-20-17-16-50-14_df198e732186825

**Comment by gozarman** [comment]
Wow, such a valuable contribution @zhongfq! good job pal.
I will review it asap.

**Comment by gozarman** [comment]
It was such a great PR. 
Thanks for that.

I just made some minor changes to your contributions to follow the consistency of the UI.
My changes are available in [feat-multi-language](https://github.com/Gozargah/Marzban/tree/feat-multi-language) branch. Let me know

**Comment by zhongfq** [comment]
> It was such a huge PR. Thanks for that.
> 
> I just made some minor changes to your contributions to make sure the new futures follow the consistency of the UI. My changes are available in [feat-multi-language](https://github.com/Gozargah/Marzban/tree/feat-multi-language) branch.
> 
> Let me know your ideas about the new changes.

I test the [feat-multi-language](https://github.com/Gozargah/Marzban/tree/feat-multi-language) branch, I found it overflow on mobile(w=375, most mobile phone width). I think it can show status icon only when Accordion is closed, and show detail when is open, also, keep reducing the space between. 
Screenshot_2023-04-21-10-24-04-89_df198e732186825

**Comment by SaintShit** [comment]
Well done, u helped a lot.

**Pull request merged**
