### PR TITLE
refactor(subscription)

### PR DESCRIPTION
**Pull request by M03ED**
- simpler code for v2ray-json
- fix for #1127

### CODE REVIEW

**Comment by ImMohammad20000** [comment]
I think it is better to have reverse as environment variable because maybe they change the way apps loads configs in future

**Comment by M03ED** [comment]
> I think it is better to have reverse as environment variable because maybe they change the way apps loads configs in future

Should we add 11 different variable to env just for this ?

**Comment by ImMohammad20000** [comment]
> > I think it is better to have reverse as environment variable because maybe they change the way apps loads configs in future
> 
> Should we add 11 different variable to env just for this ?

we have 6 config format

- v2ray
- v2ray-json
- clash
- clash-meta
- sing-box
- outline

and as far as i know currently all xray based apps do the reversing for json format

we need one variable per format for this

**Comment by M03ED** [comment]
> we have 6 config format
> 
> - v2ray
> - v2ray-json
> - clash
> - clash-meta
> - sing-box
> - outline
> 
> and as far as i know currently all xray based apps do the reversing for json format
> 
> we need one variable per format for this

All appliances are ok 
Only problem is v2rayng , it will insert config in reverse and it will start from end of array
Because of this we decide to insert them in reverse order to be ok in v2rayng 

Also this is not about config type , this is about user agent

**Comment by ImMohammad20000** [comment]
> > we have 6 config format
> > 
> > * v2ray
> > * v2ray-json
> > * clash
> > * clash-meta
> > * sing-box
> > * outline
> > 
> > and as far as i know currently all xray based apps do the reversing for json format
> > we need one variable per format for this
> 
> All appliances are ok Only problem is v2rayng , it will insert config in reverse and it will start from end of array Because of this we decide to insert them in reverse order to be ok in v2rayng
> 
> Also this is not about config type , this is about user agent

v2rayn and Streisand do this too

**Comment by M03ED** [comment]
> v2rayn and Streisand do this too

No they don't, they show it in reverse because marzban send it in reverse

**Pull request merged**
