### PR TITLE
Fix v2ray-custom userLevel

### PR DESCRIPTION
**Pull request by fodhelper**
For policy section of v2rayNG we need to use a userLevel
i just exported an config from v2rayNG, it's default userlevel was 8 so i used 8 for default userLevel
image

### CODE REVIEW

**Comment by M03ED** [comment]
I tried v2rayn and for vless it didn't use level , and for trojan use level 1

**Comment by fodhelper** [comment]
Yes, i have exported a client config from v2rayN and it does not have it (even when statistics is enabled)
But in v2rayNG it does exist and level is 8 for all configs, it is used for Policy section when speed display is enabled from global settings

I wish there was separated template for v2rayNG and v2rayN, so i can disable logging for v2rayNG but keep it for v2rayN, and maybe some other changes

**Comment by M03ED** [comment]
I test speed display enabled with level 8 but download and upload speed is 0

**Comment by fodhelper** [comment]
Yes, that's because API inbound and settings is missing from v2rayNG exported config
So problem was not userLevel, but still Marzban must set same userLevel for all outbounds, or leave it to default 0 for trojan too

**Pull request closed without merging**
