### PR TITLE
Ability to customize all notifications

### PR DESCRIPTION
**Pull request by erfjab**
Some notifications are not necessary or pleasant for some users and cause spam. It is better to have the possibility of deactivation. i fixed this. #1153

- [x] Default is True
- [x] NOTIFY_STATUS_CHANGE
- [x] NOTIFY_USER_CREATED
- [x] NOTIFY_USER_UPDATED
- [x] NOTIFY_USER_DELETED
- [x] NOTIFY_USER_DATA_USED_RESET
- [x] NOTIFY_USER_SUB_REVOKED
- [x] NOTIFY_DATA_USAGE_PERCENT_REACHED
- [x] NOTIFY_DAYS_LEFT
- [x] NOTIFY_LOGIN

### CODE REVIEW

**Comment by fodhelper** [comment]
You can separate Failed Login Notify and Successful Login Notify
Personally, I like to know about failed logins
You can add IP and user-agent of failed login too

**Comment by erfjab** [comment]
> You can separate Failed Login Notify and Successful Login Notify
> Personally, I like to know about failed logins
> You can add IP and user-agent of failed login too

Successful/unsuccessful logins will be notified along with the user's IP. In the future, I will add more information about the user login, but for now, it is enough.

**Comment by erfjab** [comment]
#1114

**Comment by erfjab** [comment]
#1140

**Comment by mohsenzt** [comment]
تشکر چطور میتونم قبل از اتمام حجم یا تاریخ اعلان دریافت کنم
Customize all notifications
 NOTIFY_STATUS_CHANGE = True
 NOTIFY_USER_CREATED = false
 NOTIFY_USER_UPDATED = false
 NOTIFY_USER_DELETED = false
 NOTIFY_USER_DATA_USED_RESET = false
 NOTIFY_USER_SUB_REVOKED = True
 NOTIFY_IF_DATA_USAGE_PERCENT_REACHED = True
 NOTIFY_IF_DAYS_LEF_REACHED = True
 NOTIFY_LOGIN = false
 NOTIFY_DAYS_LEFT = 3
 NOTIFY_REACHED_USAGE_PERCENT = 85
 من از این موارد رو در فایل .env قرار دادم اما قبل از اتمام حجم و تاریخ بهم اطلاع نمیده

**Pull request merged**
