### PR TITLE
fix: some small bugs

### PR DESCRIPTION
**Pull request by ImMohammad20000**
- fix for #1073
-  remove random user agent for gRPC not supported by [singbox config](https://sing-box.sagernet.org/configuration/shared/v2ray-transport/#quic)
- change outbound tag to proxy in v2ray custom config
-  change `EXTERNAL_CONFIG` default value
- remove random user-agent for gRPC not supported by [clash config](https://github.com/MetaCubeX/mihomo/blob/4277dc6eab4c15aac1be4f7bd6c259efe29043f8/docs/config.yaml#L594)
- revoke subscription not update xray config in telegram bot

### CODE REVIEW

**Comment by ImMohammad20000** [comment]
#1166

**Comment by M03ED** [comment]
headers are a global variable that does not depend on network type

**Comment by ImMohammad20000** [comment]
> headers are a global variable that does not depend on network type

In singbox it creating error headers not supported

**Comment by M03ED** [comment]
Anyway this is gonna make conflict with #1165 
I will apply it there

**Comment by ImMohammad20000** [comment]
@SaintShit please merge this pr fast it fix most bugs in release v0.6.0

**Comment by ImMohammad20000** [comment]
@SaintShit :|

**Pull request closed without merging**
