### PR TITLE
don't send `keepAlivePeriod` if it not in the config

### PR DESCRIPTION
**Pull request by ImMohammad20000**

### CODE REVIEW

**Comment by iambabyninja** [comment]
hKeepAlivePeriod now in mux section

**Comment by ImMohammad20000** [comment]
> hKeepAlivePeriod now in mux section 

I know thats why i do this

**Comment by iambabyninja** [comment]
> > hKeepAlivePeriod now in mux section 
> 
> I know thats why i do this

**h**KeepAlivePeriod not KeepAlivePeriod

**Comment by ImMohammad20000** [comment]
> > > hKeepAlivePeriod now in mux section 
> > 
> > I know thats why i do this
> 
> **h**KeepAlivePeriod, not KeepAlivePeriod

I know it add in xmux 
But what about the older versions we need to support theme too

**Pull request merged**
