### PR TITLE
Complete Statistics with Minimal Design

### PR DESCRIPTION
**Pull request by Musixal**
add cpu usage to stats
reduce font sizes
change memory usage to ram for occupying less space

### CODE REVIEW

**Comment by gozarman** [comment]
Great changes, thank you so much.
There can be more details there in addition to the CPU usage that you kindly contributed.

We are thinking of a new design for the statistics section to have all the details without affecting the simplicity of the UI.
I will keep this PR open to discuss about it. I'll inform you about the progress of this feature.

Thank you so much

**Comment by Musixal** [comment]
Screenshot 2023-05-08 at 02 53 25

New Minimal Design

**Comment by pvbooy** [comment]
Hi,Open a section under Network master and add the speed of  node network there

**Comment by Lordrichard23** [comment]
This is an interesting idea, will it be added to Marzban?  Why have these changes not been applied yet?

**Comment by phoenix-marzban** [comment]
سلام وقتی در داکر برای ادیت این فایل میشویم و با نانو تغییر میدهیم کد جدید رو و سیو میکنیم و exit هیچ تغییری اعمال نمیشود و با ریستارت مرزبان همه ی تغییرات دیفالت میشود لطفا توضیح دهید چکار کنیم 

Hello, when we edit this file in docker and change it with nano, we save the new code and exit, no changes are applied, and after restarting Marzban, all changes are defaulted. Please explain what to do.

**Comment by realartin** [comment]
we need this

**Comment by realartin** [comment]
please ad auto refresh button for users and static's (every x sec can be chosen by admin on this page)

**Comment by rezazoom** [comment]
+1

**Comment by realartin** [comment]
also need this data's too : 
on users segments show which user created by which admin , and also quick look admins can be awesome "sorting each admin users individually by admin's that created users on same page by sudo admin "

**Comment by realartin** [comment]
> also need this data's too : on users segments show which user created by which admin , and also quick look admins can be awesome "sorting each admin users individually by admin's that created users on same page by sudo admin "

then other data's needed too :
when sorting by admin x for example created users on this page indeed it's needed to be added this feature that shows when user y was made and when was the lased edit and also resets , data limit , time limit changes to be shown 
also one last thing is users have been deleted by admin x should be shown on some where

**Pull request closed without merging**
