### PR TITLE
Dublicate hosts - Order Hosts - OnlineBadge Refactor

### PR DESCRIPTION
**Pull request by MatinDehghanian**
image

adding a duplicate option to hosts

### CODE REVIEW

**Comment by erfjab** [comment]
Awesome 🤌
I'm waiting for the next commit. 👀

**Comment by erfjab** [comment]
Great, thank you. ❤️

**Comment by MatinDehghanian** [comment]
image
Now u can order hosts too

**Comment by MatinDehghanian** [comment]
image
image

and now online badge colors is more friendly and pulse animation is just for online users
plus i cleaned onlinebadge.tsx to work more smooth

**Pull request merged**
