### PR TITLE
Marzban CLI documentation

### PR DESCRIPTION
**Pull request by Alirezaja1384**
import-from-env's exception handling improved and Marzabn CLI's documentation was added.

Details:
 - import-from-env: Exception handling improved
 - README.md and README-fa.md: Marzban CLI section added
 - CONTRIBUTING.md: Marzban CLI section added
 - cli/admin.py: Docstrings added and minor improvement applied
 - cli/README.md: marzban-cli documentation generated using typer-cli

### CODE REVIEW

**Comment by Alirezaja1384** [comment]
I forgot about README-fa.md. I'll probably update it in a couple of hours.

**Comment by SaintShit** [comment]
That's alright, thank you for your efforts. I'll merge it just after you're finished with README-fa

**Comment by Alirezaja1384** [comment]
I think the CLI's documentation stuff is done, but if anything is missing, I'll be happy to add it :)

**Comment by SaintShit** [comment]
This is fine 🔥

**Pull request merged**
