### PR TITLE
Update Telegram bot

### PR DESCRIPTION
**Pull request by mmdchnar**
multi admin (sudo)
search by username
charge by templates
random username
logging to channel
default VLESS flow
new view and some fix

### CODE REVIEW

**Comment by SaintShit** [comment]
Hello, thank you for your generous help. I'll test it and merge it to `dev` branch.

**Comment by mmdchnar** [comment]
i am developing this in https://github.com/mmdchnar/marzban-telebot

**Comment by SaintShit** [comment]
so you don't want to merge it with Marzban?

**Comment by mmdchnar** [comment]
After I implemented my ideas and fixed the bugs
i'll pull request to dev branch

**Comment by SaintShit** [comment]
All good, you decide. I'll close it then.

**Pull request closed without merging**
