### PR TITLE
Respect User Xray Policies

### PR DESCRIPTION
**Pull request by fodhelper**
This PR will make user's xray policies effective
Tested and safe to merge

### CODE REVIEW

**Comment by erfjab** [comment]
Good idea, some users need it.

**Comment by erfjab** [comment]
ok , thank you.

**Comment by ImMohammad20000** [comment]
I didn't understand is this merge the user policy and the hard coded one togetger?

**Comment by ImMohammad20000** [comment]
it better to have merge_dicts as private functions in XrayConfig class

**Comment by ImMohammad20000** [comment]
> It just overrides user's Xray policy settings with the hardcoded policy settings
Ok

**Comment by xmohammad1** [comment]
thanks for pr , thats useful

**Pull request merged**
