### PR TITLE
Reduce subscription link length

### PR DESCRIPTION
**Pull request by fodhelper**
This PR reduces subscription link
from :
`https://www.example.com/sub/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0LTAxIiwiYWNjZXNzIjoic3Vic2NyaXB0aW9uIiwiaWF0IjoxNzA5MjE1MTUzfQ.omAlMh79ff1f5Btz9Ygt4JR9Gv4ZFfxtrm0-hoUkuew`
to
`https://www.example.com/sub/eyJzdWIiOiJ0ZXN0LTAxIiwiYWNjZXNzIjoic3ViIiwiaWF0IjoxNzA5MjE1MTUzfQ.omAlMh79ff1f5Btz9Ygt4JR9Gv4ZFfxtrm0-hoUkuew`

difference is 51 characters

old links will still work with no problem

### CODE REVIEW

**Comment by M03ED** [comment]
Still to long , not much different

**Comment by fodhelper** [comment]
Current difference is 51 characters!
Do you have any idea with JWT to reduce it even more?

**Comment by M03ED** [comment]
> Current difference is 51 characters! Do you have any idea with JWT to reduce it even more?

in mu opinion there is no different between long and short sub link because you never gonna type it , you just copy it or use qr code

**Comment by fodhelper** [comment]
yes, it's not that much important, but it's not that much useless too
As you said this PR's result is not short enough, i made another one without JWT, i will share it soon

**Pull request closed without merging**
