### PR TITLE
Update Subscription index.html

### PR DESCRIPTION
**Pull request by M03ED**
DateTime was based on Coordinated Universal Time, but this was not mentioned

### CODE REVIEW

**Comment by M03ED** [comment]
image

**Comment by SaintShit** [comment]
Hi, the image of apps are not loaded, and I think it'd be better to load them from their repository or their app store image

**Comment by M03ED** [comment]
i think about this but i didnt remember any service we can upload photos to use them 
google play is blocked in iran right now and there is chance app store be blocked again so we cant use them
so i choose github to do this
also i add clash verge and add both googleplay and github link for users dont have access to free internet

**Comment by M03ED** [comment]
image

**Comment by M03ED** [comment]
i think we don't need this pr anymore.

**Pull request closed without merging**
