### PR TITLE
Persian language

### PR DESCRIPTION
**Pull request by MuhammadAshouri**
I added Persian language support to Marzban. But there is still some style issues with Rtl theme. I hope others could contribute and fix those.
I'm not pro in React; So I hope this changes couldn't be all wrong

image

### CODE REVIEW

**Comment by SaintShit** [comment]
Hi, I'm gonna pick `fa.json` only, as the front-end changes have styling issues. I leave the styling changes to @gozarman

**Comment by SaintShit** [comment]
please send your configuration for this inbound if you can ( with including serverName )

**Comment by MuhammadAshouri** [comment]
> please send your configuration for this inbound if you can ( with including serverName )

What configuration?

**Comment by SaintShit** [comment]
@MuhammadAshouri xray

**Comment by MuhammadAshouri** [comment]
> @MuhammadAshouri xray

I just added fa.json :-/
I have no idea what are you talking about😅

**Comment by SaintShit** [comment]
@MuhammadAshouri Oh. sorry. I mistakenly commented here. I was gonna reply to one of the issues 😅😅

**Comment by SaintShit** [comment]
Hi, why did you close this? can you re-open PR to push fa.json again?

**Pull request closed without merging**
