### PR TITLE
fix: syntax warnings in python 3.12

### PR DESCRIPTION
**Pull request by ImMohammad20000**

### CODE REVIEW

**Comment by Tili1420** [comment]
I update marzban dev but got error according pictute
20241124-12-24-50-AM
please fix this

**Comment by ImMohammad20000** [comment]
> I update marzban dev but got error according pictute 20241124-12-24-50-AM please fix this

can you send error text

**Comment by Tili1420** [comment]
marzban-1     | INFO:     162.158.111.219:19998 - "GET /api/system HTTP/1.1" 500 Internal Server Error
marzban-1     | ERROR:    Exception in ASGI application
marzban-1     | Traceback (most recent call last):
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
marzban-1     |     self.dialect.do_execute(
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
marzban-1     |     cursor.execute(statement, parameters)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
marzban-1     |     result = self._query(query)
marzban-1     |              ^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
marzban-1     |     conn.query(q)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
marzban-1     |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
marzban-1     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
marzban-1     |     result.read()
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
marzban-1     |     first_packet = self.connection._read_packet()
marzban-1     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
marzban-1     |     packet.raise_for_error()
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
marzban-1     |     err.raise_mysql_exception(self._data)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
marzban-1     |     raise errorclass(errno, errval)
marzban-1     | pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(users.online_at) >= '2024-11-23 05:52:39.529508'' at line 3")
marzban-1     |
marzban-1     | The above exception was the direct cause of the following exception:
marzban-1     |
marzban-1     | Traceback (most recent call last):
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
marzban-1     |     result = await app(  # type: ignore[func-returns-value]
marzban-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
marzban-1     |     return await self.app(scope, receive, send)
marzban-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
marzban-1     |     await super().__call__(scope, receive, send)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
marzban-1     |     await self.middleware_stack(scope, receive, send)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
marzban-1     |     raise exc
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
marzban-1     |     await self.app(scope, receive, _send)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
marzban-1     |     await self.app(scope, receive, send)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
marzban-1     |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
marzban-1     |     raise exc
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
marzban-1     |     await app(scope, receive, sender)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
marzban-1     |     await self.middleware_stack(scope, receive, send)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
marzban-1     |     await route.handle(scope, receive, send)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
marzban-1     |     await self.app(scope, receive, send)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
marzban-1     |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
marzban-1     |     raise exc
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
marzban-1     |     await app(scope, receive, sender)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
marzban-1     |     response = await f(request)
marzban-1     |                ^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
marzban-1     |     raw_response = await run_endpoint_function(
marzban-1     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
marzban-1     |     return await run_in_threadpool(dependant.call, **values)
marzban-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
marzban-1     |     return await anyio.to_thread.run_sync(func, *args)
marzban-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/anyio/to_thread.py", line 31, in run_sync
marzban-1     |     return await get_asynclib().run_sync_in_worker_thread(
marzban-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
marzban-1     |     return await future
marzban-1     |            ^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 867, in run
marzban-1     |     result = context.run(func, *args)
marzban-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/code/app/routers/system.py", line 43, in get_system_stats
marzban-1     |     online_users = crud.count_online_users(db, 24)
marzban-1     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/code/app/db/crud.py", line 1489, in count_online_users
marzban-1     |     return query.scalar()
marzban-1     |            ^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2892, in scalar
marzban-1     |     ret = self.one()
marzban-1     |           ^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2869, in one
marzban-1     |     return self._iter().one()
marzban-1     |            ^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2915, in _iter
marzban-1     |     result = self.session.execute(
marzban-1     |              ^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
marzban-1     |     result = conn._execute_20(statement, params or {}, execution_options)
marzban-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
marzban-1     |     return meth(self, args_10style, kwargs_10style, execution_options)
marzban-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
marzban-1     |     return connection._execute_clauseelement(
marzban-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
marzban-1     |     ret = self._execute_context(
marzban-1     |           ^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
marzban-1     |     self._handle_dbapi_exception(
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
marzban-1     |     util.raise_(
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
marzban-1     |     raise exception
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
marzban-1     |     self.dialect.do_execute(
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
marzban-1     |     cursor.execute(statement, parameters)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
marzban-1     |     result = self._query(query)
marzban-1     |              ^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
marzban-1     |     conn.query(q)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
marzban-1     |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
marzban-1     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
marzban-1     |     result.read()
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
marzban-1     |     first_packet = self.connection._read_packet()
marzban-1     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
marzban-1     |     packet.raise_for_error()
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
marzban-1     |     err.raise_mysql_exception(self._data)
marzban-1     |   File "/usr/local/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
marzban-1     |     raise errorclass(errno, errval)
marzban-1     | sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(users.online_at) >= '2024-11-23 05:52:39.529508'' at line 3")
marzban-1     | [SQL: SELECT count(users.id) AS count_1
marzban-1     | FROM users
marzban-1     | WHERE users.online_at IS NOT NULL AND datetime(users.online_at) >= %(datetime_1)s]
marzban-1     | [parameters: {'datetime_1': datetime.datetime(2024, 11, 23, 5, 52, 39, 529508)}]
marzban-1     | (Background on this error at: https://sqlalche.me/e/14/f405)

**Comment by ImMohammad20000** [comment]
> marzban-1 | INFO: 162.158.111.219:19998 - "GET /api/system HTTP/1.1" 500 Internal Server Error marzban-1 | ERROR: Exception in ASGI application marzban-1 | Traceback (most recent call last): marzban-1 | File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context marzban-1 | self.dialect.do_execute( marzban-1 | File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute marzban-1 | cursor.execute(statement, parameters) marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute marzban-1 | result = self._query(query) marzban-1 | ^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query marzban-1 | conn.query(q) marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query marzban-1 | self._affected_rows = self._read_query_result(unbuffered=unbuffered) marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result marzban-1 | result.read() marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read marzban-1 | first_packet = self.connection._read_packet() marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet marzban-1 | packet.raise_for_error() marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error marzban-1 | err.raise_mysql_exception(self._data) marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception marzban-1 | raise errorclass(errno, errval) marzban-1 | pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(users.online_at) >= '2024-11-23 05:52:39.529508'' at line 3") marzban-1 | marzban-1 | The above exception was the direct cause of the following exception: marzban-1 | marzban-1 | Traceback (most recent call last): marzban-1 | File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi marzban-1 | result = await app( # type: ignore[func-returns-value] marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in **call** marzban-1 | return await self.app(scope, receive, send) marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in **call** marzban-1 | await super().**call**(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 113, in **call** marzban-1 | await self.middleware_stack(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in **call** marzban-1 | raise exc marzban-1 | File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in **call** marzban-1 | await self.app(scope, receive, _send) marzban-1 | File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in **call** marzban-1 | await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in **call** marzban-1 | await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app marzban-1 | raise exc marzban-1 | File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app marzban-1 | await app(scope, receive, sender) marzban-1 | File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 715, in **call** marzban-1 | await self.middleware_stack(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 735, in app marzban-1 | await route.handle(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle marzban-1 | await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app marzban-1 | await wrap_app_handling_exceptions(app, request)(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app marzban-1 | raise exc marzban-1 | File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app marzban-1 | await app(scope, receive, sender) marzban-1 | File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app marzban-1 | response = await f(request) marzban-1 | ^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app marzban-1 | raw_response = await run_endpoint_function( marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 214, in run_endpoint_function marzban-1 | return await run_in_threadpool(dependant.call, **values) marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool marzban-1 | return await anyio.to_thread.run_sync(func, *args) marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/anyio/to_thread.py", line 31, in run_sync marzban-1 | return await get_asynclib().run_sync_in_worker_thread( marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread marzban-1 | return await future marzban-1 | ^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 867, in run marzban-1 | result = context.run(func, *args) marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/code/app/routers/system.py", line 43, in get_system_stats marzban-1 | online_users = crud.count_online_users(db, 24) marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/code/app/db/crud.py", line 1489, in count_online_users marzban-1 | return query.scalar() marzban-1 | ^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2892, in scalar marzban-1 | ret = self.one() marzban-1 | ^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2869, in one marzban-1 | return self._iter().one() marzban-1 | ^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2915, in _iter marzban-1 | result = self.session.execute( marzban-1 | ^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1714, in execute marzban-1 | result = conn._execute_20(statement, params or {}, execution_options) marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20 marzban-1 | return meth(self, args_10style, kwargs_10style, execution_options) marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection marzban-1 | return connection._execute_clauseelement( marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement marzban-1 | ret = self._execute_context( marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context marzban-1 | self._handle_dbapi_exception( marzban-1 | File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception marzban-1 | util.raise_( marzban-1 | File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 210, in raise_ marzban-1 | raise exception marzban-1 | File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context marzban-1 | self.dialect.do_execute( marzban-1 | File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute marzban-1 | cursor.execute(statement, parameters) marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute marzban-1 | result = self._query(query) marzban-1 | ^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query marzban-1 | conn.query(q) marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query marzban-1 | self._affected_rows = self._read_query_result(unbuffered=unbuffered) marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result marzban-1 | result.read() marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read marzban-1 | first_packet = self.connection._read_packet() marzban-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet marzban-1 | packet.raise_for_error() marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error marzban-1 | err.raise_mysql_exception(self._data) marzban-1 | File "/usr/local/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception marzban-1 | raise errorclass(errno, errval) marzban-1 | sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(users.online_at) >= '2024-11-23 05:52:39.529508'' at line 3") marzban-1 | [SQL: SELECT count(users.id) AS count_1 marzban-1 | FROM users marzban-1 | WHERE users.online_at IS NOT NULL AND datetime(users.online_at) >= %(datetime_1)s] marzban-1 | [parameters: {'datetime_1': datetime.datetime(2024, 11, 23, 5, 52, 39, 529508)}] marzban-1 | (Background on this error at: https://sqlalche.me/e/14/f405)

update and test

**Comment by Tili1420** [comment]
thanks a lot its got ok

**Pull request merged**
