### PR TITLE
Read SplitHTTP Settings from Template if there is any

### PR DESCRIPTION
**Pull request by fodhelper**
If user add any setting for SplitHTTP in the template, Marzban will use it instead of core or default settings (but by default there is no SplitHTTP settings in the Template file, so will not make any problem for anyone)
Fixes https://github.com/Gozargah/Marzban/issues/1277 and makes users able to fix https://github.com/Gozargah/Marzban/issues/1279 by setting custom settings in the Template file

### CODE REVIEW

**Comment by M03ED** [comment]
this can be good for temporary use but cant solve this 
https://github.com/Gozargah/Marzban/issues/1277#issuecomment-2323106616

**Comment by M03ED** [comment]
As you said it should be a range 
https://github.com/Gozargah/Marzban/issues/1277#issuecomment-2323058459
Wait a few days and I will find a way for this

**Comment by ImMohammad20000** [comment]
This pr hase a merge conflicts can fix it

**Comment by M03ED** [comment]
I have an idea to refactor this part completely but it needs some change in front end

**Pull request closed without merging**
