### PR TITLE
Added 4 archtype inbounds example

### PR DESCRIPTION
**Pull request by ImMohammad20000**
Added 4 archtype inbounds example so it wont cause problems for newly created users

### CODE REVIEW

**Review by htesadeghi — COMMENTED** [review]
good and the following review ...

**Comment by iambabyninja** [comment]
If you think someone will come in and configure something, you’re mistaken. People will simply use VLESS without encryption and vmess in the way you specified because it will connect for them.
Especially now, when there are tons of great tools for generating/editing inbounds.

**Comment by ImMohammad20000** [comment]
> If you think someone will come in and configure something, you’re mistaken. People will simply use VLESS without encryption and vmess in the way you specified because it will connect for them.


No the marzban logic require that to have all form of protocols so if you add another inbound of a protocol it assign that to the user


> Nothing bad has happened since we removed the configuration. Many users learned for the first time that there’s a “core settings” button. But it’s fine, everyone managed the setup, especially now, with so many great tools available for generating/editing inbounds.

If you read the configuration i wrote it only 4 simple tcp config with some random port there is no reality no tls config noting

**Comment by mikeesierrah** [comment]
Nothing bad happened ? i created many users through api and since there was no vmess inbound from the start i cant add vmess or trojan or other configuration to the users that didnt have it since marzban wont add it to users if it wasnt created in the panel

**Comment by iambabyninja** [comment]
> 
> 
> Nothing bad happened ? i created many users through api and since there was no vmess inbound from the start i cant add vmess or trojan or other configuration to the users that didnt have it since marzban wont add it to users if it wasnt created in the panel 
> 
> 
> 
> 
> 
> 
> 
> and now marzbans official bot cant handle that many users  and crashes when i want to change this many users
> 
> 

The absence of a basic config is relevant only for new installations.

If you are creating users via the API with Trojan and VMESS protocols and don’t have these configurations, it’s not an issue of the panel, but of the person creating it.
If you want to use these protocols – simply add them.

Don’t invent problems out of thin air.

The situation with the removal of the demo config showed that most users didn’t even know there was a “core settings” button and that each protocol required configuration.

Moreover, there is now a requirement for panels to have no pre-configured values.

**Comment by mikeesierrah** [comment]
> Don’t invent problems out of thin air.

it is a real problem - my panel didn't have VMess configs and suddenly i wanted to add a VMess config to the users but i couldn't since it want created at first 

is it so hard to understand ?  in Marzban when you add a new config to the panel it will be added to every user even old ones

but since you deleted it from the start the proxy arch-type wasnt created for them so it wont add the new ones of those types 

just create a panel and try you'd see the difference between version 5 and 6

**Comment by M03ED** [comment]
> it is a real problem - my panel didn't have VMess configs and suddenly i wanted to add a VMess config to the users but i couldn't since it want created at first 
> 
> is it so hard to understand ?  in Marzban when you add a new config to the panel it will be added to every user even old ones
> 
> but since you deleted it from the start the proxy arch-type wasnt created for them so it wont add the new ones of those types 
> 
> just create a panel and try you'd see the difference between version 5 and 6 
> 
> 


You're able to configure your marzban as you need it , first configure your panel then use, simple

**Comment by mikeesierrah** [comment]
> You're able to configure your marzban as you need it , first configure your panel then use, simple
and what if i want to suddenly change inbounds?  why would you cause a problem and then try to justify it through nonesense

**Comment by mikeesierrah** [comment]
اسونه ها سختم نیست ، کافیه ی پروکسی ساده از هر ارچ تایپ باشه که بعدا کسی خواست کانفیگاشو عوض کنه واسه همه بیاد  پاکشم کنه مشکلی پیش نمیاد چون همون اول ساخته شده

پنلش با بات مرزبانی که میخواد یوزراشو تغییر بده داون نشه

**Comment by M03ED** [comment]
> and what if i want to suddenly change inbounds?  why would you cause a problem and then try to justify it through words that dont make sense

Even with old JSON file if you remove a protocol before adding a user your going to face this issue again

**Comment by mikeesierrah** [comment]
> Even with old JSON file if you remove a protocol before adding a user your going to face this issue again

No? when i create a panel it has default inbounds - i remove the default configurtaion then add my configurations 

afterwhich when i want to just change i add a new inbound  from another archtype - it will be simply added to old users since it was created from the start

**Comment by mikeesierrah** [comment]
دوستان فک کنم متوجه شدید مشکل چیست 

دوباره توضیح میدم بفهمید 

1. تو ورژن های قبلی وقتی به هسته اینباندی اضافه میشد خود به خود به تمام یوزر ها اضافه میشد مگر شدوساکس ، حتی با پاک کردن اینباند های دیفالت

3. تو اخرین اپدیت این قضیه فقط درمورد کانفیگ های ویلس صدق میکنه ، اگه بخوای کانفیگ ویمسی توی هسته ادد کنی تمام یوزر های قبلی رو باید با بات مرزبان صاف بشی تا ادد کنه 

حالا فک کن 1000 تا یوزر باشه بات مرزبان سکته میزنه 


علتش مشخصه 4 حالت دیفالت توی دیتابیس ساخته نشده ، قبلا ساخته میشد حالا پاکشم میکردی مشکلی پیش نمیومد بعدا بازم کانفیگ متفاوت میزاشتی اضافه میشد به یوزر های قدیمی 

چون اون ارچ تایپ ساخته شده بود

الان مطمئن باشم کاملا مشکل رو درک کردید؟

**Comment by M03ED** [comment]
> دوستان فک کنم متوجه شدید مشکل چیست 
> 
> دوباره توضیح میدم بفهمید 
> 
> 1. تو ورژن های قبلی وقتی به هسته اینباندی اضافه میشد خود به خود به تمام یوزر ها اضافه میشد مگر شدوساکس ، حتی با پاک کردن اینباند های دیفالت
> 
> 3. تو اخرین اپدیت این قضیه فقط درمورد کانفیگ های ویلس صدق میکنه ، اگه بخوای کانفیگ ویمسی توی هسته ادد کنی تمام یوزر های قبلی رو باید با بات مرزبان صاف بشی تا ادد کنه 
> 
> حالا فک کن 1000 تا یوزر باشه بات مرزبان سکته میزنه 
> 
> 
> علتش مشخصه 4 حالت دیفالت توی دیتابیس ساخته نشده ، قبلا ساخته میشد حالا پاکشم میکردی مشکلی پیش نمیومد بعدا بازم کانفیگ متفاوت میزاشتی اضافه میشد به یوزر های قدیمی 
> 
> چون اون ارچ تایپ ساخته شده بود
> 
> الان مطمئن باشم کاملا مشکل رو درک کردید؟

هیچوقت ساخته نمیشدن مگر در همون لحظه یک اینباند از همون پروتکل برای یوزر فعال بوده

**Comment by ImMohammad20000** [comment]
این pr باز میکنم تا روش بیشتر بحث بشه

**Comment by mikeesierrah** [comment]
> > دوستان فک کنم متوجه شدید مشکل چیست
> > دوباره توضیح میدم بفهمید
> > 
> > 1. تو ورژن های قبلی وقتی به هسته اینباندی اضافه میشد خود به خود به تمام یوزر ها اضافه میشد مگر شدوساکس ، حتی با پاک کردن اینباند های دیفالت
> > 2. تو اخرین اپدیت این قضیه فقط درمورد کانفیگ های ویلس صدق میکنه ، اگه بخوای کانفیگ ویمسی توی هسته ادد کنی تمام یوزر های قبلی رو باید با بات مرزبان صاف بشی تا ادد کنه
> > 
> > حالا فک کن 1000 تا یوزر باشه بات مرزبان سکته میزنه
> > علتش مشخصه 4 حالت دیفالت توی دیتابیس ساخته نشده ، قبلا ساخته میشد حالا پاکشم میکردی مشکلی پیش نمیومد بعدا بازم کانفیگ متفاوت میزاشتی اضافه میشد به یوزر های قدیمی
> > چون اون ارچ تایپ ساخته شده بود
> > الان مطمئن باشم کاملا مشکل رو درک کردید؟
> 
> هیچوقت ساخته نمیشدن مگر در همون لحظه یک اینباند از همون پروتکل برای یوزر فعال بوده

خب دوباره تست کردم درست میگید ، مشکل از ذهنیت اشتباه من بود تو این قضیه 

اگه دلخوری بوجود اوردم عذرمیخوام 


@ImMohammad20000 بنظرم ایشو رو ببند اشتباه میکردم تو این قضیه

**Pull request closed without merging**
